import { useState } from "react";
import Head from "next/head";

import AuthLayout from "~/modules/Auth/AuthLayout";
import LoginForm from "~/modules/Signin/LoginForm";
import SignUpForm from "~/modules/Signin/SignUpForm";

import withAuthRedirect from "~/lib/helpers/withAuthRedirect";

export type AuthMode = "login" | "register";

function Home() {
  const [mode, setMode] = useState<AuthMode>("login");

  return (
    <>
      <Head>
        <title>Pawnder</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthLayout>
        {mode === "login" ? (
          <LoginForm setMode={(mode: AuthMode) => setMode(mode)} />
        ) : (
          <SignUpForm setMode={(mode: AuthMode) => setMode(mode)} />
        )}
      </AuthLayout>
    </>
  );
}

export default withAuthRedirect(Home);
